### ISSUE TITLE
Remove the linking functionality

### ISSUE THREAD

**Issue by IvanUkhov** [blas-lapack-rs/blas-sys#17]
Hi,

There are the following two issues related to `blas-sys`, `lapack-sys`, `blas`, and `lapack`:
1. Each crate is explicitly aware of the three BLAS/LAPACK implementations that are currently available, namely, `openblas-src`, `netlib-src`, and `accelerate-src`. Each crate provides a feature for each implementation so that the user can select what is desired. The problem is that these dependencies are explicit, hardcoded. It doesn’t scale well.
2. ~~Each crate supports two types of bindings: C and Fortran. The problem is that it introduces unnecessary complexity when it comes to the usage of the crates. There are always these two modules, `c` and `fortran`, to choose from when calling a function. It’s unlikely that someone wants to use both types of bindings simultaneously.~~

I propose the following changes:
1. The crates will depend only one implementation; `openblas-src` is arguably our best choice for now. Instead of propagating N (the number of available implementations) features through the hierarchy of crates, there will be only one—let’s call it `linkage`—which will tell the low-level crates, `blas-sys` and `lapack-sys`, whether they should pull in `openblas-src`. The feature will be a default feature. In order to switch to a different implementation, the user will have to disable `linkage` and manually depend on the desired implementation, such as `netlib-src`, which will compile what’s needed and do the linkage properly.
2. ~~The crates will provide two new mutually exclusive features: `c` and `fortran`. The former will be a default feature. Depending on which one is activated, the functions from the corresponding module will be re-exported into the root module. The other module will be excluded from the compilation process.~~

I would appreciate any feedback on the above. Thank you!

@cmr and @bluss: I’m especially interested in your opinions. Thanks!

Regards,
Ivan

**Comment by bluss** [comment]
Cargo doesn't really support mutually exclusive features, which makes all of this complicated (also backend selection).

I've contemplated not having any backend at all by default. Choosing a backend should be done only once (not in any library, just in the final application) and thus it's better as opt-in rather than relying on all blas consumers to disable a default feature.

I would not make c/fortran mutually exclusive. That is also incompatible when two different crates (one needs c and one needs fortran) are linked into the same project.

**Comment by IvanUkhov** [comment]
Thanks for the reply!

> Cargo doesn't really support mutually exclusive features, which makes all of this complicated (also backend selection).

I meant more like a social contract: it’s not enforced, but that’s how it’s supposed to be used.

> I've contemplated not having any backend at all by default. Choosing a backend should be done only once (not in any library, just in the final application) and thus it's better as opt-in rather than relying on all blas consumers to disable a default feature.

We’ve started to discuss this already a couple of times (#5 and #14)  but haven’t taken any decision yet. I actually don’t mind at all dropping the default backend. If you and @cmr think that it’s a sensible thing to do, I’ll remove it.

> I would not make c/fortran mutually exclusive. That is also incompatible when two different crates (one needs c and one needs fortran) are linked into the same project.

I’m glad I asked.

**Comment by astraw** [comment]
I see this is closed but I don't see a discussion of what decision was taken. @IvanUkhov can you please clarify?

**Comment by IvanUkhov** [comment]
The decision is to keep it as it is right now.

**Comment by astraw** [comment]
By the way, I think this issue could be re-opened because I don't think it is resolved. I hadn't previously come across it, but it is pretty important I think.

**Comment by astraw** [comment]
For the past few months, I have been testing the idea of removing features from the low-level crates and having a single "implementation defining" crate which must be included in the final binary (`lapack-linkage` above). It works well, simplifies the lower-level crates, and I haven't hit any unexpected issues. Therefore, I am in support of this idea.

**Comment by IvanUkhov** [comment]
(The following is a slightly modified version of what I wrote [here](https://github.com/stainless-steel/lapack-sys/pull/8).)

I lean toward what @astraw proposes. To this end, I’ve already created [`blas-src`](https://crates.io/crates/blas-src) and [`lapack-src`](https://crates.io/crates/lapack-src). Ideally, the usage of `blas`, `blas-sys`, `lapack`, and `lapack-sys` should look as follows:

```toml
[dependencies]
blas = "0.18"
blas-src = { version = "0.1", features = ["openblas"] }
```

But one will also have to mention the linking crate in the codebase:

```rust
extern crate blas;
extern crate blas_src;
```

The next step is to remove all the features from those four main crates. However, it should first be agreed upon by those who’re actively involved in this project.

@bluss and @cmr, what are your opinions?

**Comment by termoshtt** [comment]
> Ideally, the usage of blas, blas-sys, lapack, and lapack-sys should look as follows:

I think it is rather a way to emulate current `blas-sys` does. Ideal case should be the following, right?

```toml
[dependencies]
blas = "*"
openblas-src = "*"
```

```rust
extern crate blas;
extern crate openblas_src;
```

If `blas-src` is ideal one, there is no difference except for the `blas-sys` is split into two crates.

**Comment by IvanUkhov** [comment]
@termoshtt, indeed. What do we gain by having a crate aggregating a bunch of other crates? Can anyone see any advantages?

**Comment by bluss** [comment]
cc @masonium too

I would prefer if all defaults features were removed, and we make it easy for end users to pick blas implementation.

What we recommend in ndarray is already pretty similar: https://github.com/bluss/rust-ndarray#how-to-use-with-cargo
(But it's a bit fragile! It requires coordination so that the library and the end user depend on the same blas-sys version.)

**Comment by termoshtt** [comment]
Could you give me a sample Cargo.toml using `blas-src` for a library which *must* depends on BLAS? Should such libraries independent from blas-src?

**Comment by astraw** [comment]
I see an advantage to creating default crate that holds (likely a rather complex and brittle) build.rs to do compile time selection of lapack/blas implementations. The advantage is that this default crate can be used in examples to usually (but likely not always) "just work" on a wide variety of architectures. I guess this crate will need to be updated fairly often to accommodate new implementations and new system configurations.

That said, such a default crate will be an opt-in, because any final binary will have to explicitly depend on this default linkage crate or else will have to explicitly depend on another linkage crate (e.g. a more specific one that doesn't try to automatically select an implementation).
